---

# Role: OpenMPI
# Install OpenMPI

- name: add path for OpenMPI to system-wide bashrc
  blockinfile:
    path: /etc/bash.bashrc
    block: |
      MPIROOT=/usr/mpi/gcc/openmpi-4.0.4rc3
      PATH=$MPIROOT/bin:$PATH
      LD_LIBRARY_PATH=$MPIROOT/lib:$LD_LIBRARY_PATH
      MANPATH=$MPIROOT/share/man:$MANPATH
      export MPIROOT PATH LD_LIBRARY_PATH MANPATH



#bench: osu-micro-benchmarks-5.8
#mpicc: /usr/mpi/gcc/openmpi-4.0.4rc3/bin/mpicc
#mpicxx: /usr/mpi/gcc/openmpi-4.0.4rc3/bin/mpicxx
#benchdir: /home/example
#
## Download and build OSU Micro Benchmarks as an example
#- name: get OSU Micro-benchmarks
#  get_url:
#    url: "https://mvapich.cse.ohio-state.edu/download/mvapich/{{ bench }}.tgz"
#    dest: /tmp
#
#- name: create directory to put the bench marks
#  file:
#    path: "{{ benchdir }}"
#    state: directory
#    mode: "0755"
#
#- name: decompress OSU Micro-benchmarks
#  unarchive:
#    src: "/tmp/{{ bench }}.tgz"
#    dest: "{{ benchdir }}"
#    remote_src: yes
#
#- name: configure OSU Micro-benchmarks
#  command: "./configure CC={{ mpicc }} CXX={{ mpicxx }} chdir={{ benchdir }}/{{ bench }}"
#
#- name: make OSU Micro-benchmarks
#  command: "make CC={{ mpicc }} CXX={{ mpicxx }} chdir={{ benchdir }}/{{ bench }}"
#
