- name: copy cudnn packages to the virtual machine
  copy:
    src: "{{ item }}"
    dest: /tmp
  with_items:
  - ../files/libcudnn8_8.2.2.26-1+cuda11.4_amd64.deb
  - ../files/libcudnn8-dev_8.2.2.26-1+cuda11.4_amd64.deb

- name: apt update
  apt:
    update_cache: yes

- name: install cudnn libraries
  apt:
    deb: "{{ item }}"
  with_items:
      - /tmp/libcudnn8_8.2.2.26-1+cuda11.4_amd64.deb
      - /tmp/libcudnn8-dev_8.2.2.26-1+cuda11.4_amd64.deb

- name: install cudnn dependent libraries
  apt:
    update_cache: yes
    name:
      - cuda-cudart-11-4
      - cuda-cudart-dev-11-4
      - libcublas-11-4
      - libcublas-dev-11-4
      - libcusolver-11-4
      - libcusolver-dev-11-4
      - libcusparse-11-4
      - libcusparse-dev-11-4
